/*L
 *  Copyright SAIC, Ellumen and RSNA (CTP)
 *
 *
 *  Distributed under the OSI-approved BSD 3-Clause License.
 *  See http://ncip.github.com/national-biomedical-image-archive/LICENSE.txt for details.
 */

<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>QA_Tool_View_Imges_TestCase</title>
</head>
<body>
<table cellpadding="1" cellspacing="1" border="1">
<thead>
<tr><td rowspan="1" colspan="3">QA_Tool_View_Imges_TestCase</td></tr>
</thead><tbody>
<tr>
	<td>open</td>
	<td>/ncia/</td>
	<td></td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>link=CLICKING HERE</td>
	<td></td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>MAINbody:loginForm:_id127</td>
	<td></td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>link=QA Tool</td>
	<td></td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>SUBmenu:treeForm:lazyAjaxTree:0:2:t2</td>
	<td></td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>//a[contains(text(),'Collection:&nbsp;&nbsp;IDRI')]</td>
	<td></td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>//a[contains(text(),'Patient:&nbsp;&nbsp;1.3.6.1.4.1.9328.50.3.0001')]</td>
	<td></td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>//a[contains(text(),'Study:&nbsp;&nbsp;1.3.6.1.4.1.9328.50.3.3')]</td>
	<td></td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>//a[contains(text(),'Series:&nbsp;&nbsp;1.3.6.1.4.1.9328.50.3.4')]</td>
	<td></td>
</tr>
<tr>
	<td>click</td>
	<td>MAINbody:mainForm:imageTable:0:_id76</td>
	<td></td>
</tr>
<tr>
	<td>waitForPopUp</td>
	<td>jpeg_window</td>
	<td>30000</td>
</tr>
<tr>
	<td>click</td>
	<td>MAINbody:mainForm:imageTable:0:_id78</td>
	<td></td>
</tr>
<tr>
	<td>waitForPopUp</td>
	<td>dicom_window</td>
	<td>30000</td>
</tr>
<tr>
	<td>click</td>
	<td>MAINbody:mainForm:imageTable:0:_id80</td>
	<td></td>
</tr>
<tr>
	<td>waitForPopUp</td>
	<td>history_window</td>
	<td>30000</td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>//a[contains(text(),'Patient:&nbsp;&nbsp;1.3.6.1.4.1.9328.50.3.0015')]</td>
	<td></td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>//a[contains(text(),'Study:&nbsp;&nbsp;1.3.6.1.4.1.9328.50.3.46')]</td>
	<td></td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>link=Show Images</td>
	<td></td>
</tr>
<tr>
	<td>click</td>
	<td>MAINbody:mainForm:imageTable:0:_id76</td>
	<td></td>
</tr>
<tr>
	<td>waitForPopUp</td>
	<td>jpeg_window</td>
	<td>30000</td>
</tr>
<tr>
	<td>click</td>
	<td>MAINbody:mainForm:imageTable:0:_id78</td>
	<td></td>
</tr>
<tr>
	<td>waitForPopUp</td>
	<td>dicom_window</td>
	<td>30000</td>
</tr>
<tr>
	<td>click</td>
	<td>MAINbody:mainForm:imageTable:0:_id80</td>
	<td></td>
</tr>
<tr>
	<td>waitForPopUp</td>
	<td>history_window</td>
	<td>30000</td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>SUBmenu:treeForm:lazyAjaxTree:0:2:0:t2</td>
	<td></td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>//a[contains(text(),'Collection:&nbsp;&nbsp;ISPY')]</td>
	<td></td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>//a[contains(text(),'Patient:&nbsp;&nbsp;35')]</td>
	<td></td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>link=Show Series</td>
	<td></td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>link=Show Images</td>
	<td></td>
</tr>
<tr>
	<td>click</td>
	<td>MAINbody:mainForm:imageTable:0:_id76</td>
	<td></td>
</tr>
<tr>
	<td>waitForPopUp</td>
	<td>jpeg_window</td>
	<td>30000</td>
</tr>
<tr>
	<td>click</td>
	<td>MAINbody:mainForm:imageTable:0:_id78</td>
	<td></td>
</tr>
<tr>
	<td>waitForPopUp</td>
	<td>dicom_window</td>
	<td>30000</td>
</tr>
<tr>
	<td>click</td>
	<td>MAINbody:mainForm:imageTable:0:_id80</td>
	<td></td>
</tr>
<tr>
	<td>waitForPopUp</td>
	<td>history_window</td>
	<td>30000</td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>link=Next</td>
	<td></td>
</tr>
<tr>
	<td>click</td>
	<td>MAINbody:mainForm:imageTable:26:_id76</td>
	<td></td>
</tr>
<tr>
	<td>waitForPopUp</td>
	<td>jpeg_window</td>
	<td>30000</td>
</tr>
<tr>
	<td>click</td>
	<td>MAINbody:mainForm:imageTable:26:_id78</td>
	<td></td>
</tr>
<tr>
	<td>waitForPopUp</td>
	<td>dicom_window</td>
	<td>30000</td>
</tr>
<tr>
	<td>click</td>
	<td>MAINbody:mainForm:imageTable:26:_id80</td>
	<td></td>
</tr>
<tr>
	<td>waitForPopUp</td>
	<td>history_window</td>
	<td>30000</td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>link=>></td>
	<td></td>
</tr>
<tr>
	<td>click</td>
	<td>MAINbody:mainForm:imageTable:38:_id76</td>
	<td></td>
</tr>
<tr>
	<td>waitForPopUp</td>
	<td>jpeg_window</td>
	<td>30000</td>
</tr>
<tr>
	<td>click</td>
	<td>MAINbody:mainForm:imageTable:41:_id78</td>
	<td></td>
</tr>
<tr>
	<td>waitForPopUp</td>
	<td>dicom_window</td>
	<td>30000</td>
</tr>
<tr>
	<td>click</td>
	<td>MAINbody:mainForm:imageTable:41:_id80</td>
	<td></td>
</tr>
<tr>
	<td>waitForPopUp</td>
	<td>history_window</td>
	<td>30000</td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>SUBmenu:treeForm:lazyAjaxTree:0:2:1:t2</td>
	<td></td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>//a[contains(text(),'Collection:&nbsp;&nbsp;LIDC')]</td>
	<td></td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>//a[contains(text(),'Patient:&nbsp;&nbsp;1.3.6.1.4.1.9328.50.3.0023')]</td>
	<td></td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>link=Show Series</td>
	<td></td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>link=Show Images</td>
	<td></td>
</tr>
<tr>
	<td>click</td>
	<td>MAINbody:mainForm:imageTable:4:_id76</td>
	<td></td>
</tr>
<tr>
	<td>waitForPopUp</td>
	<td>jpeg_window</td>
	<td>30000</td>
</tr>
<tr>
	<td>click</td>
	<td>MAINbody:mainForm:imageTable:4:_id78</td>
	<td></td>
</tr>
<tr>
	<td>waitForPopUp</td>
	<td>dicom_window</td>
	<td>30000</td>
</tr>
<tr>
	<td>click</td>
	<td>MAINbody:mainForm:imageTable:4:_id80</td>
	<td></td>
</tr>
<tr>
	<td>waitForPopUp</td>
	<td>history_window</td>
	<td>30000</td>
</tr>
<tr>
	<td>selectAndWait</td>
	<td>MAINbody:mainForm:_id59</td>
	<td>label=10</td>
</tr>
<tr>
	<td>click</td>
	<td>MAINbody:mainForm:imageTable:25:_id76</td>
	<td></td>
</tr>
<tr>
	<td>waitForPopUp</td>
	<td>jpeg_window</td>
	<td>30000</td>
</tr>
<tr>
	<td>click</td>
	<td>MAINbody:mainForm:imageTable:25:_id78</td>
	<td></td>
</tr>
<tr>
	<td>waitForPopUp</td>
	<td>dicom_window</td>
	<td>30000</td>
</tr>
<tr>
	<td>click</td>
	<td>MAINbody:mainForm:imageTable:25:_id80</td>
	<td></td>
</tr>
<tr>
	<td>waitForPopUp</td>
	<td>history_window</td>
	<td>30000</td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>//a[contains(text(),'Patient:&nbsp;&nbsp;1.3.6.1.4.1.9328.50.3.0106')]</td>
	<td></td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>link=Show Series</td>
	<td></td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>link=Show Images</td>
	<td></td>
</tr>
<tr>
	<td>selectAndWait</td>
	<td>MAINbody:mainForm:_id62</td>
	<td>label=6</td>
</tr>
<tr>
	<td>click</td>
	<td>MAINbody:mainForm:imageTable:19:_id76</td>
	<td></td>
</tr>
<tr>
	<td>waitForPopUp</td>
	<td>jpeg_window</td>
	<td>30000</td>
</tr>
<tr>
	<td>click</td>
	<td>MAINbody:mainForm:imageTable:19:_id78</td>
	<td></td>
</tr>
<tr>
	<td>waitForPopUp</td>
	<td>dicom_window</td>
	<td>30000</td>
</tr>
<tr>
	<td>click</td>
	<td>MAINbody:mainForm:imageTable:13:_id80</td>
	<td></td>
</tr>
<tr>
	<td>waitForPopUp</td>
	<td>history_window</td>
	<td>30000</td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>SUBmenu:treeForm:lazyAjaxTree:0:2:2:t2</td>
	<td></td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>//a[contains(text(),'Collection:&nbsp;&nbsp;RIDER')]</td>
	<td></td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>//a[contains(text(),'Patient:&nbsp;&nbsp;1.3.6.1.4.1.9328.50.1.0010')]</td>
	<td></td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>//a[@onclick="document.forms['MAINbody:mainForm']['MAINbody:mainForm:_idcl'].value='MAINbody:mainForm:studyView:resultTable:2:_id102'; document.forms['MAINbody:mainForm'].submit(); return false;"]</td>
	<td></td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>//a[@onclick="document.forms['MAINbody:mainForm']['MAINbody:mainForm:_idcl'].value='MAINbody:mainForm:seriesView:resultTable:1:_id123'; document.forms['MAINbody:mainForm'].submit(); return false;"]</td>
	<td></td>
</tr>
<tr>
	<td>click</td>
	<td>MAINbody:mainForm:imageTable:1:_id76</td>
	<td></td>
</tr>
<tr>
	<td>waitForPopUp</td>
	<td>jpeg_window</td>
	<td>30000</td>
</tr>
<tr>
	<td>click</td>
	<td>MAINbody:mainForm:imageTable:1:_id78</td>
	<td></td>
</tr>
<tr>
	<td>waitForPopUp</td>
	<td>dicom_window</td>
	<td>30000</td>
</tr>
<tr>
	<td>click</td>
	<td>MAINbody:mainForm:imageTable:1:_id80</td>
	<td></td>
</tr>
<tr>
	<td>waitForPopUp</td>
	<td>history_window</td>
	<td>30000</td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>SUBmenu:treeForm:lazyAjaxTree:0:2:3:t2</td>
	<td></td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>//a[contains(text(),'Collection:&nbsp;&nbsp;Virtual Colonoscopy')]</td>
	<td></td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>link=Show Series</td>
	<td></td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>link=Show Images</td>
	<td></td>
</tr>
<tr>
	<td>click</td>
	<td>MAINbody:mainForm:imageTable:14:_id76</td>
	<td></td>
</tr>
<tr>
	<td>waitForPopUp</td>
	<td>jpeg_window</td>
	<td>30000</td>
</tr>
<tr>
	<td>click</td>
	<td>MAINbody:mainForm:imageTable:14:_id78</td>
	<td></td>
</tr>
<tr>
	<td>waitForPopUp</td>
	<td>dicom_window</td>
	<td>30000</td>
</tr>
<tr>
	<td>click</td>
	<td>MAINbody:mainForm:imageTable:14:_id80</td>
	<td></td>
</tr>
<tr>
	<td>waitForPopUp</td>
	<td>history_window</td>
	<td>30000</td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>SUBmenu:treeForm:lazyAjaxTree:0:2:4:t2</td>
	<td></td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>SUBmenu:treeForm:lazyAjaxTree:0:2:t2</td>
	<td></td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>SUBmenu:treeForm:lazyAjaxTree:0:1:t2</td>
	<td></td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>//a[contains(text(),'Collection:&nbsp;&nbsp;LIDC')]</td>
	<td></td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>link=Show Studies</td>
	<td></td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>link=Show Series</td>
	<td></td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>link=Show Images</td>
	<td></td>
</tr>
<tr>
	<td>click</td>
	<td>MAINbody:mainForm:imageTable:8:_id76</td>
	<td></td>
</tr>
<tr>
	<td>waitForPopUp</td>
	<td>jpeg_window</td>
	<td>30000</td>
</tr>
<tr>
	<td>click</td>
	<td>MAINbody:mainForm:imageTable:8:_id78</td>
	<td></td>
</tr>
<tr>
	<td>waitForPopUp</td>
	<td>dicom_window</td>
	<td>30000</td>
</tr>
<tr>
	<td>click</td>
	<td>MAINbody:mainForm:imageTable:8:_id80</td>
	<td></td>
</tr>
<tr>
	<td>waitForPopUp</td>
	<td>history_window</td>
	<td>30000</td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>//a[contains(text(),'Collection:&nbsp;&nbsp;RIDER')]</td>
	<td></td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>//a[contains(text(),'Patient:&nbsp;&nbsp;1.3.6.1.4.1.9328.50.2.0001')]</td>
	<td></td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>link=Show Series</td>
	<td></td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>link=Show Images</td>
	<td></td>
</tr>
<tr>
	<td>click</td>
	<td>MAINbody:mainForm:imageTable:9:_id76</td>
	<td></td>
</tr>
<tr>
	<td>waitForPopUp</td>
	<td>jpeg_window</td>
	<td>30000</td>
</tr>
<tr>
	<td>click</td>
	<td>MAINbody:mainForm:imageTable:9:_id78</td>
	<td></td>
</tr>
<tr>
	<td>waitForPopUp</td>
	<td>dicom_window</td>
	<td>30000</td>
</tr>
<tr>
	<td>click</td>
	<td>MAINbody:mainForm:imageTable:9:_id80</td>
	<td></td>
</tr>
<tr>
	<td>waitForPopUp</td>
	<td>history_window</td>
	<td>30000</td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>SUBmenu:treeForm:lazyAjaxTree:0:1:t2</td>
	<td></td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>SUBmenu:treeForm:lazyAjaxTree:0:0:t2</td>
	<td></td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>//a[contains(text(),'Collection:&nbsp;&nbsp;IDRI')]</td>
	<td></td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>//a[contains(text(),'Patient:&nbsp;&nbsp;1.3.6.1.4.1.9328.50.10.0005')]</td>
	<td></td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>//a[@onclick="document.forms['MAINbody:mainForm']['MAINbody:mainForm:_idcl'].value='MAINbody:mainForm:studyView:resultTable:5:_id102'; document.forms['MAINbody:mainForm'].submit(); return false;"]</td>
	<td></td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>//a[@onclick="document.forms['MAINbody:mainForm']['MAINbody:mainForm:_idcl'].value='MAINbody:mainForm:seriesView:resultTable:4:_id123'; document.forms['MAINbody:mainForm'].submit(); return false;"]</td>
	<td></td>
</tr>
<tr>
	<td>click</td>
	<td>MAINbody:mainForm:imageTable:9:_id76</td>
	<td></td>
</tr>
<tr>
	<td>waitForPopUp</td>
	<td>jpeg_window</td>
	<td>30000</td>
</tr>
<tr>
	<td>click</td>
	<td>MAINbody:mainForm:imageTable:9:_id78</td>
	<td></td>
</tr>
<tr>
	<td>waitForPopUp</td>
	<td>dicom_window</td>
	<td>30000</td>
</tr>
<tr>
	<td>click</td>
	<td>MAINbody:mainForm:imageTable:9:_id80</td>
	<td></td>
</tr>
<tr>
	<td>waitForPopUp</td>
	<td>history_window</td>
	<td>30000</td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>SUBmenu:treeForm:lazyAjaxTree:0:0:t2</td>
	<td></td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>SUBmenu:treeForm:lazyAjaxTree:0:0:t2</td>
	<td></td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>SUBmenu:treeForm:lazyAjaxTree:0:0:0:t2</td>
	<td></td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>//a[contains(text(),'Collection:&nbsp;&nbsp;RIDER')]</td>
	<td></td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>//a[@onclick="document.forms['MAINbody:mainForm']['MAINbody:mainForm:_idcl'].value='MAINbody:mainForm:patientView:resultTable:6:_id81'; document.forms['MAINbody:mainForm'].submit(); return false;"]</td>
	<td></td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>//a[@onclick="document.forms['MAINbody:mainForm']['MAINbody:mainForm:_idcl'].value='MAINbody:mainForm:studyView:resultTable:6:_id102'; document.forms['MAINbody:mainForm'].submit(); return false;"]</td>
	<td></td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>link=Show Images</td>
	<td></td>
</tr>
<tr>
	<td>click</td>
	<td>MAINbody:mainForm:imageTable:1:_id76</td>
	<td></td>
</tr>
<tr>
	<td>waitForPopUp</td>
	<td>jpeg_window</td>
	<td>30000</td>
</tr>
<tr>
	<td>click</td>
	<td>MAINbody:mainForm:imageTable:1:_id78</td>
	<td></td>
</tr>
<tr>
	<td>waitForPopUp</td>
	<td>dicom_window</td>
	<td>30000</td>
</tr>
<tr>
	<td>click</td>
	<td>MAINbody:mainForm:imageTable:1:_id80</td>
	<td></td>
</tr>
<tr>
	<td>waitForPopUp</td>
	<td>history_window</td>
	<td>30000</td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>SUBmenu:treeForm:lazyAjaxTree:0:0:1:t2</td>
	<td></td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>link=LOGOUT</td>
	<td></td>
</tr>

</tbody></table>
</body>
</html>
