/*L
 *  Copyright SAIC, Ellumen and RSNA (CTP)
 *
 *
 *  Distributed under the OSI-approved BSD 3-Clause License.
 *  See http://ncip.github.com/national-biomedical-image-archive/LICENSE.txt for details.
 */

package org.nih.nci.cagrid.aim.service.globus;

import org.nih.nci.cagrid.aim.service.AIMDataServiceImpl;

import java.rmi.RemoteException;

/** 
 * DO NOT EDIT:  This class is autogenerated!
 *
 * This class implements each method in the portType of the service.  Each method call represented
 * in the port type will be then mapped into the unwrapped implementation which the user provides
 * in the AIMDataServiceImpl class.  This class handles the boxing and unboxing of each method call
 * so that it can be correclty mapped in the unboxed interface that the developer has designed and 
 * has implemented.  Authorization callbacks are automatically made for each method based
 * on each methods authorization requirements.
 * 
 * @created by Introduce Toolkit version 1.3
 * 
 */
public class AIMDataServiceProviderImpl{
	
	AIMDataServiceImpl impl;
	
	public AIMDataServiceProviderImpl() throws RemoteException {
		impl = new AIMDataServiceImpl();
	}
	

    public org.nih.nci.cagrid.aim.stubs.SubmitResponse submit(org.nih.nci.cagrid.aim.stubs.SubmitRequest params) throws RemoteException, gov.nih.nci.cagrid.data.faults.QueryProcessingExceptionType, gov.nih.nci.cagrid.data.faults.MalformedQueryExceptionType {
    org.nih.nci.cagrid.aim.stubs.SubmitResponse boxedResult = new org.nih.nci.cagrid.aim.stubs.SubmitResponse();
    impl.submit(params.getXmls());
    return boxedResult;
  }

    public org.nih.nci.cagrid.aim.stubs.QueryByTransferResponse queryByTransfer(org.nih.nci.cagrid.aim.stubs.QueryByTransferRequest params) throws RemoteException, gov.nih.nci.cagrid.data.faults.QueryProcessingExceptionType, gov.nih.nci.cagrid.data.faults.MalformedQueryExceptionType {
    org.nih.nci.cagrid.aim.stubs.QueryByTransferResponse boxedResult = new org.nih.nci.cagrid.aim.stubs.QueryByTransferResponse();
    boxedResult.setTransferServiceContextReference(impl.queryByTransfer(params.getCqlQuery().getCQLQuery()));
    return boxedResult;
  }

    public org.nih.nci.cagrid.aim.stubs.SubmitByTransferResponse submitByTransfer(org.nih.nci.cagrid.aim.stubs.SubmitByTransferRequest params) throws RemoteException, gov.nih.nci.cagrid.data.faults.QueryProcessingExceptionType, gov.nih.nci.cagrid.data.faults.MalformedQueryExceptionType {
    org.nih.nci.cagrid.aim.stubs.SubmitByTransferResponse boxedResult = new org.nih.nci.cagrid.aim.stubs.SubmitByTransferResponse();
    boxedResult.setTransferServiceContextReference(impl.submitByTransfer());
    return boxedResult;
  }

}
