/*L
 *  Copyright SAIC, Ellumen and RSNA (CTP)
 *
 *
 *  Distributed under the OSI-approved BSD 3-Clause License.
 *  See http://ncip.github.com/national-biomedical-image-archive/LICENSE.txt for details.
 */

package gov.nih.nci.cagrid.ncia.service.globus.resource;

import gov.nih.nci.cagrid.introduce.servicetools.SingletonResourceHomeImpl;
import gov.nih.nci.cagrid.ncia.common.NCIACoreServiceConstants;
import gov.nih.nci.cagrid.ncia.stubs.NCIACoreServiceResourceProperties;

import org.apache.axis.components.uuid.UUIDGen;
import org.apache.axis.components.uuid.UUIDGenFactory;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.globus.wsrf.InvalidResourceKeyException;
import org.globus.wsrf.PersistenceCallback;
import org.globus.wsrf.Resource;
import org.globus.wsrf.ResourceContext;
import org.globus.wsrf.ResourceException;
import org.globus.wsrf.ResourceKey;
import org.globus.wsrf.jndi.Initializable;


/**
 * DO NOT EDIT:  This class is autogenerated!
 *
 * This class implements the resource home for the resource type represented
 * by this service.
 *
 * @created by Introduce Toolkit version 1.2
 *
 */
public class NCIACoreServiceResourceHome extends SingletonResourceHomeImpl implements Initializable {

	static final Log logger = LogFactory.getLog(NCIACoreServiceResourceHome.class);
    private static final UUIDGen UUIDGEN = UUIDGenFactory.getUUIDGen();

	public Resource createSingleton() {
		logger.info("Creating a single resource.");
		try {
		    NCIACoreServiceResourceProperties props = new NCIACoreServiceResourceProperties();
			NCIACoreServiceResource resource = new NCIACoreServiceResource();
			if (resource instanceof PersistenceCallback) {
			      //try to load the resource if it was persisted
                  try{
                    ((PersistenceCallback) resource).load(null);
			      } catch (InvalidResourceKeyException ex){
			      	  //persisted singleton resource was not found so we will just create a new one
			          resource.initialize(props, NCIACoreServiceConstants.RESOURCE_PROPERTY_SET, UUIDGEN.nextUUID());
			      }
            } else {
                    resource.initialize(props, NCIACoreServiceConstants.RESOURCE_PROPERTY_SET, UUIDGEN.nextUUID());
            }

			return resource;
		} catch (Exception e) {
			logger.error("Exception when creating the resource",e);
			return null;
		}
	}


	public Resource find(ResourceKey key) throws ResourceException {
		NCIACoreServiceResource resource = (NCIACoreServiceResource) super.find(key);
		return resource;
	}


	/**
	 * Initialze the singleton resource, when the home is initialized.
	 */
	public void initialize() throws Exception {
		logger.info("Attempting to initialize resource.");
		Resource resource = find(null);
		if (resource == null) {
			logger.error("Unable to initialize resource!");
		} else {
			logger.info("Successfully initialized resource.");
		}
	}

    /**
     * Get the resouce that is being addressed in this current context
     */
    public NCIACoreServiceResource getAddressedResource() throws Exception {
        NCIACoreServiceResource thisResource;
        thisResource = (NCIACoreServiceResource) ResourceContext.getResourceContext().getResource();
        return thisResource;
    }
}