/*L
 *  Copyright SAIC, Ellumen and RSNA (CTP)
 *
 *
 *  Distributed under the OSI-approved BSD 3-Clause License.
 *  See http://ncip.github.com/national-biomedical-image-archive/LICENSE.txt for details.
 */

/**
 * TraceProvider.java
 *
 * This file was generated by MapForce 2011r2sp1.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the MapForce Documentation for further details.
 * http://www.altova.com/mapforce
 */


package com.altova;


public abstract class TraceProvider {
	protected TraceTarget traceTarget = null;

	protected void writeTrace(String info) {
		if (traceTarget != null)
			traceTarget.writeTrace(info);
	}

	public void registerTraceTarget(TraceTarget newTraceTarget) {
		traceTarget = newTraceTarget;
	}

	public void unregisterTraceTarget() {
		traceTarget = null;
	}
}
