/*L
   Copyright SAIC, Ellumen and RSNA (CTP)


   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/national-biomedical-image-archive/LICENSE.txt for details.
L*/

ALTER TABLE CSM_APPLICATION MODIFY  DECLARATIVE_FLAG NUMBER(1) DEFAULT 0 NOT NULL ;
ALTER TABLE CSM_PROTECTION_ELEMENT DROP COLUMN PROTECTION_ELEMENT_TYPE_ID;
ALTER TABLE CSM_PROTECTION_ELEMENT ADD PROTECTION_ELEMENT_TYPE VARCHAR(100);
ALTER TABLE CSM_PG_PE MODIFY  UPDATE_DATE DATE NULL;
ALTER TABLE CSM_PROTECTION_ELEMENT ADD ( CONSTRAINT UQ_PE_OBJ_ID_ATTR_APP_ID UNIQUE (PROTECTION_ELEMENT_NAME, ATTRIBUTE, APPLICATION_ID));

ALTER TABLE CSM_APPLICATION MODIFY APPLICATION_NAME varchar2(255) ;
ALTER TABLE CSM_GROUP MODIFY GROUP_NAME varchar2(255) ;
ALTER TABLE CSM_APPLICATION ADD DATABASE_URL VARCHAR(100);
ALTER TABLE CSM_APPLICATION ADD DATABASE_USER_NAME VARCHAR(100);
ALTER TABLE CSM_APPLICATION ADD DATABASE_PASSWORD VARCHAR(100);
ALTER TABLE CSM_APPLICATION ADD DATABASE_DIALECT VARCHAR(100);
ALTER TABLE CSM_APPLICATION ADD DATABASE_DRIVER VARCHAR(100);


UPDATE csm_application SET csm_application.DECLARATIVE_FLAG='0';
UPDATE csm_pg_pe SET UPDATE_DATE=NULL;


ALTER TABLE CSM_USER_GROUP_ROLE_PG DROP CONSTRAINT FK_USER_GROUP_ROLE_PG_GROUP;

ALTER TABLE CSM_USER_GROUP_ROLE_PG ADD ( CONSTRAINT FK_USER_GROUP_ROLE_PG_GROUP FOREIGN KEY (GROUP_ID) REFERENCES CSM_GROUP (GROUP_ID) ON DELETE CASCADE );


update csm_application set application_name='csmupt' where application_id=2;


update csm_protection_element set object_id='csmupt', protection_element_name='csmupt';
where protection_element_id=1;

update csm_protection_element set application_id=2 where protection_element_name='NCIA';
commit;
