function FileData_Pairs(x)
{
x.t("working","data");
x.t("items","level");
x.t("add","items");
x.t("results","working");
x.t("results","nbia");
x.t("nbia","add");
x.t("search","results");
x.t("review","search");
x.t("viewing","search");
x.t("basket","working");
x.t("basket","review");
x.t("basket","viewing");
x.t("basket","subsequent");
x.t("level","data");
x.t("data","basket");
x.t("subsequent","download");
}
