function FileData_Pairs(x)
{
x.t("(upt)","ncicb");
x.t("user","provisioning");
x.t("support","personnel");
x.t("overview","nbia");
x.t("overview","administration");
x.t("nbia","assigned");
x.t("nbia","administration");
x.t("functions","overview");
x.t("assigned","using");
x.t("privileges","nbia");
x.t("tool","(upt)");
x.t("provisioning","tool");
x.t("application","support");
x.t("administration","functions");
x.t("administration","privileges");
x.t("administration","administration");
x.t("ncicb","application");
x.t("using","user");
}
