/*L
 *  Copyright SAIC, Ellumen and RSNA (CTP)
 *
 *
 *  Distributed under the OSI-approved BSD 3-Clause License.
 *  See http://ncip.github.com/national-biomedical-image-archive/LICENSE.txt for details.
 */

/**
 * core/get_position_of_last_delimiter_recursive.java
 *
 * This file was generated by MapForce 2011r2sp1.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the MapForce Documentation for further details.
 * http://www.altova.com/mapforce
 */
package com.mapforce.core;
import com.altova.mapforce.*;
import com.altova.types.*;
import com.altova.xml.*;
import java.util.*;

public class get_position_of_last_delimiter_recursive extends com.altova.TraceProvider 
{

	
	static class main implements IEnumerable
	{
		java.lang.String var1_filepath;
		java.math.BigDecimal var2_pos;
		java.lang.String var3_delimiter1;
		java.lang.String var4_delimiter2;
	
		public main(java.lang.String var1_filepath, java.math.BigDecimal var2_pos, java.lang.String var3_delimiter1, java.lang.String var4_delimiter2)
		{
			this.var1_filepath = var1_filepath;
			this.var2_pos = var2_pos;
			this.var3_delimiter1 = var3_delimiter1;
			this.var4_delimiter2 = var4_delimiter2;
		}

		public IEnumerator enumerator() {return new Enumerator(this);}
		
		public static class Enumerator implements IEnumerator
		{
			int pos = 0;
			int state = 2;
			Object current;
			main closure;
			java.math.BigDecimal var5_subtract;
			java.lang.String var6_substring;
			public Enumerator(main closure) 
			{
				this.closure = closure;
			}
			
			public Object current() {return current;}
			
			public int position() {return pos;}
			
			public boolean moveNext() throws Exception
			{
				while (state != 0)
				{
					switch (state) 
					{
					case 2:	if (moveNext_2()) return true; break;
					case 3:	if (moveNext_3()) return true; break;
					case 6:	if (moveNext_6()) return true; break;
 					}
				}
				return false;
			}

			private boolean moveNext_2() throws Exception {
				state = 0;				
				if (!(com.altova.functions.Core.equal(closure.var2_pos, new java.math.BigDecimal("0")))) {state = 3; return false; }
				current = new java.math.BigDecimal("0");
				pos++;
				return true;
			}
			private boolean moveNext_3() throws Exception {
				state = 0;				
				var5_subtract = com.altova.functions.Core.subtract(closure.var2_pos, new java.math.BigDecimal("1"));
				var6_substring = com.altova.functions.Core.substring(closure.var1_filepath, com.altova.CoreTypes.decimalToDouble(var5_subtract), com.altova.CoreTypes.parseDouble("1"));
				if (!(com.altova.functions.Core.logicalOr(com.altova.functions.Core.equal(var6_substring, closure.var3_delimiter1), com.altova.functions.Core.equal(var6_substring, closure.var4_delimiter2)))) {state = 6; return false; }
				current = var5_subtract;
				pos++;
				return true;
			}
			private boolean moveNext_6() throws Exception {
				state = 0;				
				current = (java.math.BigDecimal)com.altova.functions.Core.first(com.mapforce.core.get_position_of_last_delimiter_recursive.create(closure.var1_filepath, var5_subtract, closure.var3_delimiter1, closure.var4_delimiter2));
				pos++;
				return true;
			}

			
			public void close()
			{
				try
				{
				}
				catch (Exception e)
				{
				}
			}
		}
				
	}



	// instances


	public static IEnumerable create(java.lang.String var1_filepath, java.math.BigDecimal var2_pos, java.lang.String var3_delimiter1, java.lang.String var4_delimiter2)
	{
		return new main(
			var1_filepath,
			var2_pos,
			var3_delimiter1,
			var4_delimiter2
			);

	}
	

}
