package gov.nih.nci.cagrid.ncia.common;

import javax.xml.namespace.QName;


/**
 * This class is autogenerated, DO NOT EDIT
 *
 * @created by Introduce Toolkit version 1.3
 */
public interface NCIACoreServiceConstantsBase {
	public static final String SERVICE_NS = "http://ncia.cagrid.nci.nih.gov/NCIACoreService";
	public static final QName RESOURCE_KEY = new QName(SERVICE_NS, "NCIACoreServiceKey");
	public static final QName RESOURCE_PROPERTY_SET = new QName(SERVICE_NS, "NCIACoreServiceResourceProperties");
	public static final QName DOMAINMODEL = new QName("gme://caGrid.caBIG/1.0/gov.nih.nci.cagrid.metadata.dataservice", "DomainModel");
	public static final QName SERVICEMETADATA = new QName("gme://caGrid.caBIG/1.0/gov.nih.nci.cagrid.metadata", "ServiceMetadata");
	
}
