/*L
 *  Copyright SAIC, Ellumen and RSNA (CTP)
 *
 *
 *  Distributed under the OSI-approved BSD 3-Clause License.
 *  See http://ncip.github.com/national-biomedical-image-archive/LICENSE.txt for details.
 */

/**
 * MappingConsole.java
 *
 * This file was generated by MapForce 2011r2sp1.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the MapForce Documentation for further details.
 * http://www.altova.com/mapforce
 */


package com.mapforce;

import com.altova.types.*;
import com.altova.io.*;
import java.io.File;
import java.io.InputStream;
import java.io.FileInputStream;
import java.io.InputStreamReader;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.BufferedReader;



public class MappingConsole {

	public static void main(String[] args) {
		System.out.println("Mapping Application");


		try { // Mapping
			TraceTargetConsole ttc = new TraceTargetConsole();
			MappingMapToAIM_v3_rv9_XML MappingMapToAIM_v3_rv9_XMLObject = new MappingMapToAIM_v3_rv9_XML();
			MappingMapToAIM_v3_rv9_XMLObject.registerTraceTarget(ttc);

			{
				//String filePath = "C:/workspace_nbia/software/cedaraAIMMapping/map/cedaraAIMtest2.xml";
				String filePath = args[0];
				System.out.println("Transform "+ filePath);
				String xmlcontent="";
				File file = new File(filePath);

				long length = file.length();
				byte[] array = new byte[(int) length];
				InputStream in = new FileInputStream(file);
				long offset = 0;
				while (offset < length) {
					int count = in.read(array, (int) offset,
							(int) (length - offset));
					offset += length;
				}
				in.close();

				//xmlcontent = new String(array, "UTF-8");
				xmlcontent = new String(array, "UTF-16");
				//System.out.println("!!!!!!xmlcontent="+xmlcontent);
				String regex= "xsi:schemaLocation=\"gme://caCORE.caCORE/3.2/edu.northwestern.radiology.AIM C:/workspace_nbia/nbia-aim/cederaAIM/AIM_v2_rv15_XML.xsd\" xmlns=\"gme://caCORE.caCORE/3.2/edu.northwestern.radiology.AIM\"";
				xmlcontent = xmlcontent.replaceAll(regex, "");
				String regex2 = "xmlns=\"gme://caCORE.caCORE/3.2/edu.northwestern.radiology.AIM\"";
				xmlcontent = xmlcontent.replaceAll(regex2, "");
				xmlcontent = xmlcontent.replaceAll("n1:", "");
				//String regex3 = "xsi:schemaLocation=\"xsi:schemaLocation=\"gme://caCORE.caCORE/3.2/edu.northwestern.radiology.AIM C:/workspace_nbia/nbia-aim/cederaAIM/AIM_v2_rv15_XML.xsd\"";
				//xmlcontent.replaceAll(regex3, "");
				String regex4 = "xmlns:n1=\"gme://caCORE.caCORE/3.2/edu.northwestern.radiology.AIM\"";
				xmlcontent = xmlcontent.replace(regex4, "");
				//System.out.println("xmlcontent="+xmlcontent);
				
				com.altova.io.Input generatedAIMSchema112Source = new com.altova.io.StringInput(xmlcontent);
				//com.altova.io.Input generatedAIMSchema112Source = com.altova.io.StreamInput.createInput("C:/workspace_nbia/software/cedaraAIMMapping/map/cedaraAIM.xml");
				MappingMapToAIM_v3_rv9_XMLObject.run(
						generatedAIMSchema112Source);
			}

			System.out.println("Finished");
		} 
		catch (com.altova.UserException ue) 
		{
			System.out.print("USER EXCEPTION:");
			System.out.println( ue.getMessage() );
			System.exit(1);
		}
		catch (com.altova.AltovaException e)
		{
			System.out.print("ERROR: ");
			System.out.println( e.getMessage() );
			if (e.getInnerException() != null)
			{
				System.out.print("Inner exception: ");
				System.out.println(e.getInnerException().getMessage());
				if (e.getInnerException().getCause() != null)
				{
					System.out.print("Cause: ");
					System.out.println(e.getInnerException().getCause().getMessage());
				}
			}
			System.out.println("\nStack Trace: ");
			e.printStackTrace();
			System.exit(1);
		}
		
		catch (Exception e) {
			System.out.print("ERROR: ");
			System.out.println( e.getMessage() );
			System.out.println("\nStack Trace: ");
			e.printStackTrace();
			System.exit(1);
		}

	}
}


class TraceTargetConsole implements com.altova.TraceTarget {
	public void writeTrace(String info) {
		System.out.println(info);
	}
}
