function FileData_Pairs(x)
{
x.t("searching","images");
x.t("saved","search");
x.t("describes","search");
x.t("initiating","searches");
x.t("remote","search");
x.t("sites","working");
x.t("working","saved");
x.t("images","searching");
x.t("images","section");
x.t("images","topics");
x.t("nbia","database");
x.t("searches","specifying");
x.t("searches","applications");
x.t("search","sites");
x.t("search","nbia");
x.t("search","queries");
x.t("queries","initiating");
x.t("section","describes");
x.t("section","include");
x.t("database","images");
x.t("performing","searches");
x.t("include","performing");
x.t("specifying","remote");
x.t("topics","section");
}
