/*L
 *  Copyright SAIC, Ellumen and RSNA (CTP)
 *
 *
 *  Distributed under the OSI-approved BSD 3-Clause License.
 *  See http://ncip.github.com/national-biomedical-image-archive/LICENSE.txt for details.
 */

function FileData_Pairs(x)
{
x.t("endorsement","listed");
x.t("study","patient");
x.t("below","selected");
x.t("available","internet");
x.t("internet","images");
x.t("digital","imaging");
x.t("digital","image");
x.t("medical","image");
x.t("http://medical.nema.org/","below");
x.t("downloaded","view");
x.t("pda","http://rsb.info.nih.gov/ij/");
x.t("weight","anatomic");
x.t("provided","convenience");
x.t("imagej","runs");
x.t("workstation","http://www.clearcanvas.ca/dnn/creations/pacsworkstation/tabid/64/default.aspx");
x.t("osirix","runs");
x.t("repository","stored");
x.t("listed","viewers");
x.t("mac","mac");
x.t("mac","windows");
x.t("mac","osx");
x.t("file","stores");
x.t("http://www.osirix-viewer.com/","clearcanvas");
x.t("results","obtaining");
x.t("images","nbia");
x.t("images","vivo");
x.t("zaurus","pda");
x.t("stored","medical");
x.t("nbia","repository");
x.t("standard","digital");
x.t("search","results");
x.t("contain","metadata");
x.t("vivo","image");
x.t("viewers","available");
x.t("viewers","provided");
x.t("viewers","imagej");
x.t("viewers","images");
x.t("viewers","viewing");
x.t("viewers","dicom");
x.t("viewers","obtaining");
x.t("metadata","image");
x.t("selected","links");
x.t("viewing","search");
x.t("communications","medicine");
x.t("freeware","dicom");
x.t("stores","digital");
x.t("http://rsb.info.nih.gov/ij/","osirix");
x.t("medicine","(dicom)");
x.t("forth","information");
x.t("windows","sharp");
x.t("dicom","http://medical.nema.org/");
x.t("dicom","file");
x.t("dicom","viewers");
x.t("dicom","image");
x.t("imaging","communications");
x.t("(dicom)","dicom");
x.t("sharp","zaurus");
x.t("osx","http://www.osirix-viewer.com/");
x.t("obtaining","dicom");
x.t("view","using");
x.t("runs","mac");
x.t("runs","linux");
x.t("linux","mac");
x.t("along","series");
x.t("site","forth");
x.t("convenience","endorsement");
x.t("information","dicom");
x.t("archive","downloaded");
x.t("image","standard");
x.t("image","viewers");
x.t("image","along");
x.t("image","archive");
x.t("image","patient");
x.t("tags","contain");
x.t("patient","study");
x.t("patient","weight");
x.t("links","freeware");
x.t("using","viewers");
x.t("series","tags");
x.t("anatomic","site");
x.t("clearcanvas","workstation");
}
