/*L
 *  Copyright SAIC, Ellumen and RSNA (CTP)
 *
 *
 *  Distributed under the OSI-approved BSD 3-Clause License.
 *  See http://ncip.github.com/national-biomedical-image-archive/LICENSE.txt for details.
 */

function FileData_Pairs(x)
{
x.t("searching","images");
x.t("searching","nbia");
x.t("responsibilities","permissions");
x.t("introduce","ncia");
x.t("appendix","contains");
x.t("defines","acronyms");
x.t("description","nbia");
x.t("table","contents");
x.t("home","page");
x.t("instructions","searching");
x.t("sites","significant");
x.t("getting","started");
x.t("contents","index");
x.t("designed","introduce");
x.t("need","know");
x.t("images","nbia");
x.t("images","topics");
x.t("results","nbia");
x.t("results","topics");
x.t("browse","online");
x.t("overview","ncia");
x.t("url","references");
x.t("features","help");
x.t("books","online");
x.t("nbia","home");
x.t("nbia","nbia");
x.t("nbia","glossary");
x.t("nbia","database");
x.t("nbia","online");
x.t("nbia","topics");
x.t("nbia","administration");
x.t("searches","submitting");
x.t("references","appendix");
x.t("welcome","national");
x.t("glossary","defines");
x.t("glossary","glossary");
x.t("biomedical","imaging");
x.t("search","results");
x.t("search","features");
x.t("started","nbia");
x.t("permissions","url");
x.t("techniques","submitting");
x.t("national","biomedical");
x.t("(nbia)","welcome");
x.t("(nbia)","following");
x.t("know","ncia");
x.t("top-level","books");
x.t("viewing","search");
x.t("index","search");
x.t("submitting","images");
x.t("login","instructions");
x.t("database","searches");
x.t("database","viewing");
x.t("imaging","archive");
x.t("variety","subtopics");
x.t("subtopics","designed");
x.t("include","brief");
x.t("brief","overview");
x.t("ncia","description");
x.t("ncia","getting");
x.t("ncia","describe");
x.t("process","searching");
x.t("view","results");
x.t("online","help");
x.t("help","table");
x.t("help","variety");
x.t("help","information");
x.t("help","learn");
x.t("page","login");
x.t("archive","(nbia)");
x.t("urls","sites");
x.t("information","using");
x.t("topics","top-level");
x.t("topics","include");
x.t("topics","describe");
x.t("administration","nbia");
x.t("administration","topics");
x.t("administration","roles");
x.t("significant","nbia");
x.t("following","topics");
x.t("used","nbia");
x.t("using","nbia");
x.t("acronyms","used");
x.t("describe","techniques");
x.t("describe","process");
x.t("describe","view");
x.t("describe","administration");
x.t("describe","concepts");
x.t("roles","responsibilities");
x.t("learn","browse");
x.t("concepts","need");
x.t("contains","urls");
}
