/*L
 *  Copyright SAIC, Ellumen and RSNA (CTP)
 *
 *
 *  Distributed under the OSI-approved BSD 3-Clause License.
 *  See http://ncip.github.com/national-biomedical-image-archive/LICENSE.txt for details.
 */

function FileData_Pairs(x)
{
x.t("available","submissions");
x.t("annotation","annotation");
x.t("annotation","submission");
x.t("annotation","submitted");
x.t("files","counts");
x.t("submission","results");
x.t("submission","report");
x.t("submission","reports");
x.t("table","submitted");
x.t("description","annotation");
x.t("patient/study/series","during");
x.t("patient/study/series","least");
x.t("submissions","made");
x.t("displays","report");
x.t("older","4.3");
x.t("count","annotations");
x.t("count","patient/study");
x.t("start","date");
x.t("new","annotation");
x.t("collection/site","exception");
x.t("during","specified");
x.t("during","date");
x.t("results","nbia");
x.t("images","affected");
x.t("specified","collection/site");
x.t("specified","date");
x.t("counts","available");
x.t("counts","fields");
x.t("range","specified");
x.t("range","corrected");
x.t("range","collection");
x.t("nbia","displays");
x.t("nbia","older");
x.t("nbia","administration");
x.t("prior","start");
x.t("fields","description");
x.t("fields","appear");
x.t("contain","count");
x.t("corrected","image");
x.t("collection","site");
x.t("viewing","annotation");
x.t("viewing","submission");
x.t("annotations","submitted");
x.t("against","versions");
x.t("report","annotation");
x.t("report","nbia");
x.t("report","submitted");
x.t("report","described");
x.t("report","contains");
x.t("reports","annotation");
x.t("reports","contain");
x.t("appear","report");
x.t("least","new");
x.t("made","against");
x.t("exception","affected");
x.t("site","fields");
x.t("query","viewing");
x.t("image","patient/study/series");
x.t("submitted","files");
x.t("submitted","query");
x.t("submitted","system");
x.t("submitted","affected");
x.t("described","following");
x.t("administration","viewing");
x.t("date","range");
x.t("following","table");
x.t("system","prior");
x.t("patient/study","series");
x.t("series","images");
x.t("versions","nbia");
x.t("affected","patient/study/series");
x.t("affected","during");
x.t("affected","counts");
x.t("contains","count");
}
