/*L
 *  Copyright SAIC, Ellumen and RSNA (CTP)
 *
 *
 *  Distributed under the OSI-approved BSD 3-Clause License.
 *  See http://ncip.github.com/national-biomedical-image-archive/LICENSE.txt for details.
 */

function FileData_Pairs(x)
{
x.t("provide","sources");
x.t("internet","options");
x.t("nci-related","bioinformatics");
x.t("table","option");
x.t("description","information");
x.t("home","displays");
x.t("home","page");
x.t("sidebar","quick");
x.t("sidebar","displayed");
x.t("displays","nbia");
x.t("displays","nci");
x.t("displays","ncicb");
x.t("left","sidebar");
x.t("getting","started");
x.t("menu","options");
x.t("nbia","home");
x.t("nbia","viewers");
x.t("nbia","portal");
x.t("nbia","news");
x.t("nbia","using");
x.t("window","n/a");
x.t("window","using");
x.t("started","nbia");
x.t("nbia-","nci-related");
x.t("quick","links");
x.t("viewers","provide");
x.t("portal","quick");
x.t("options","lower");
x.t("options","described");
x.t("lower","left");
x.t("option","description");
x.t("n/a","quick");
x.t("displayed","nbia");
x.t("sources","nbia-");
x.t("page","home");
x.t("page","left");
x.t("page","separate");
x.t("bioinformatics","information");
x.t("separate","window");
x.t("information","internet");
x.t("information","quick");
x.t("described","following");
x.t("nci","home");
x.t("ncicb","home");
x.t("links","getting");
x.t("links","menu");
x.t("links","nbia");
x.t("links","quick");
x.t("links","nci");
x.t("links","ncicb");
x.t("following","table");
x.t("news","displays");
x.t("news","page");
x.t("using","nbia");
}
