/*L
 *  Copyright SAIC, Ellumen and RSNA (CTP)
 *
 *
 *  Distributed under the OSI-approved BSD 3-Clause License.
 *  See http://ncip.github.com/national-biomedical-image-archive/LICENSE.txt for details.
 */

function FileData_Pairs(x)
{
x.t("available","nbia");
x.t("managing","data");
x.t("table","option");
x.t("description","information");
x.t("home","page");
x.t("home","returns");
x.t("remote","sites");
x.t("remote","search");
x.t("remote","image");
x.t("sites","page");
x.t("sites","specifying");
x.t("sites","manage");
x.t("bar","managing");
x.t("bar","home");
x.t("bar","getting");
x.t("bar","top");
x.t("bar","welcome/home");
x.t("displays","simple");
x.t("displays","search");
x.t("displays","separate");
x.t("displays","data");
x.t("getting","started");
x.t("consists","options");
x.t("contents","side");
x.t("top","menu");
x.t("menu","bar");
x.t("images","displays");
x.t("simple","search");
x.t("nbia","home");
x.t("nbia","configured");
x.t("nbia","online");
x.t("nbia","using");
x.t("nbia","returns");
x.t("window","using");
x.t("search","remote");
x.t("search","sites");
x.t("search","displays");
x.t("search","images");
x.t("search","page");
x.t("started","nbia");
x.t("configured","remote");
x.t("choosing","data");
x.t("options","described");
x.t("side","menu");
x.t("function","available");
x.t("basket","displays");
x.t("basket","view");
x.t("basket","page");
x.t("basket","help");
x.t("option","description");
x.t("option","choosing");
x.t("performing","simple");
x.t("logs","nbia");
x.t("n/a","search");
x.t("view","contents");
x.t("page","home");
x.t("page","consists");
x.t("page","menu");
x.t("page","function");
x.t("page","performing");
x.t("page","option");
x.t("page","n/a");
x.t("specifying","remote");
x.t("help","displays");
x.t("help","window");
x.t("help","logout");
x.t("separate","online");
x.t("online","help");
x.t("information","home");
x.t("data","basket");
x.t("image","sites");
x.t("described","following");
x.t("following","table");
x.t("manage","data");
x.t("using","nbia");
x.t("logout","logs");
x.t("returns","nbia");
x.t("welcome/home","page");
}
