/*L
 *  Copyright SAIC, Ellumen and RSNA (CTP)
 *
 *
 *  Distributed under the OSI-approved BSD 3-Clause License.
 *  See http://ncip.github.com/national-biomedical-image-archive/LICENSE.txt for details.
 */

function FileData_Pairs(x)
{
x.t("exist","system");
x.t("available","submissions");
x.t("files","counts");
x.t("submission","results");
x.t("submission","corrected");
x.t("submission","report");
x.t("submission","reports");
x.t("submission","affect");
x.t("table","submitted");
x.t("description","new");
x.t("once","time");
x.t("patient/study/series","least");
x.t("submissions","made");
x.t("displays","report");
x.t("older","4.3");
x.t("time","submission");
x.t("time","original");
x.t("time","frame");
x.t("time","image");
x.t("count","patients");
x.t("count","incremented");
x.t("count","patient/study");
x.t("original","image");
x.t("new","image");
x.t("frame","count");
x.t("frame","reports");
x.t("collection/site","exception");
x.t("during","specified");
x.t("during","date");
x.t("results","nbia");
x.t("results","display");
x.t("images","affected");
x.t("specified","collection/site");
x.t("specified","date");
x.t("counts","available");
x.t("counts","fields");
x.t("studies","series");
x.t("range","specified");
x.t("range","collection");
x.t("nbia","displays");
x.t("nbia","older");
x.t("nbia","administration");
x.t("patient/","study/series");
x.t("fields","description");
x.t("fields","appear");
x.t("patients","studies");
x.t("contain","count");
x.t("selected","fields");
x.t("display","count");
x.t("corrected","time");
x.t("corrected","patient/");
x.t("corrected","image");
x.t("collection","site");
x.t("viewing","submission");
x.t("viewing","image");
x.t("whether","subsequent");
x.t("against","versions");
x.t("report","nbia");
x.t("report","image");
x.t("report","submitted");
x.t("report","described");
x.t("reports","contain");
x.t("reports","image");
x.t("appear","report");
x.t("successfully","submitted");
x.t("affect","whether");
x.t("least","new");
x.t("least","image");
x.t("made","against");
x.t("incremented","affected");
x.t("study/series","patient/study/series");
x.t("exception","affected");
x.t("considered","corrected");
x.t("site","selected");
x.t("query","viewing");
x.t("image","exist");
x.t("image","submission");
x.t("image","successfully");
x.t("image","considered");
x.t("image","image");
x.t("image","submitted");
x.t("image","re-submitted");
x.t("submitted","files");
x.t("submitted","once");
x.t("submitted","during");
x.t("submitted","query");
x.t("described","following");
x.t("administration","viewing");
x.t("date","range");
x.t("following","table");
x.t("system","time");
x.t("patient/study","series");
x.t("series","images");
x.t("series","image");
x.t("subsequent","image");
x.t("re-submitted","time");
x.t("versions","nbia");
x.t("affected","during");
x.t("affected","counts");
x.t("affected","patient/");
}
