/*L
 *  Copyright SAIC, Ellumen and RSNA (CTP)
 *
 *
 *  Distributed under the OSI-approved BSD 3-Clause License.
 *  See http://ncip.github.com/national-biomedical-image-archive/LICENSE.txt for details.
 */

function FileData_Pairs(x)
{
x.t("searching","shared");
x.t("lists","searching");
x.t("clear","field");
x.t("sidebar","search");
x.t("user","search");
x.t("field","start");
x.t("working","data");
x.t("working","shared");
x.t("left","sidebar");
x.t("reset","clear");
x.t("link","tools");
x.t("start","again");
x.t("includes","series");
x.t("list","searching");
x.t("list","user");
x.t("list","link");
x.t("list","includes");
x.t("list","complete");
x.t("list","know");
x.t("list","viewing");
x.t("list","retrieve");
x.t("list","follow");
x.t("list","click");
x.t("list","page");
x.t("list","data");
x.t("again","search");
x.t("results","working");
x.t("name","given");
x.t("name","existing");
x.t("nbia","informs");
x.t("nbia","adds");
x.t("search","reset");
x.t("search","results");
x.t("search","shared");
x.t("search","successful");
x.t("know","exact");
x.t("viewing","search");
x.t("basket","working");
x.t("basket","shared");
x.t("retrieve","list");
x.t("launch","search");
x.t("opens","enter");
x.t("informs","displayed");
x.t("follow","steps");
x.t("steps","click");
x.t("adds","image");
x.t("exact","name");
x.t("given","shared");
x.t("click","search");
x.t("click","submit");
x.t("enter","exact");
x.t("existing","shared");
x.t("displayed","shared");
x.t("tools","left");
x.t("page","opens");
x.t("data","basket");
x.t("shared","lists");
x.t("shared","list");
x.t("image","series");
x.t("submit","launch");
x.t("successful","nbia");
x.t("series","shared");
x.t("series","visibility");
x.t("visibility","nbia");
}
