/*L
 *  Copyright SAIC, Ellumen and RSNA (CTP)
 *
 *
 *  Distributed under the OSI-approved BSD 3-Clause License.
 *  See http://ncip.github.com/national-biomedical-image-archive/LICENSE.txt for details.
 */

function FileData_Pairs(x)
{
x.t("internet","ctp");
x.t("privacy","policies");
x.t("submission","overview");
x.t("summary","process");
x.t("anonymization","script");
x.t("transfers","image");
x.t("open","tools");
x.t("(ctp)","client");
x.t("repository","alternative");
x.t("trial","processor");
x.t("file","open");
x.t("policies","ctp");
x.t("installing","ctp");
x.t("machine","filesender");
x.t("images","image");
x.t("overview","submitting");
x.t("overview","image");
x.t("overview","submit");
x.t("processor","(ctp)");
x.t("processor","client");
x.t("path","summary");
x.t("nbia","database");
x.t("nbia","using");
x.t("follows","path");
x.t("filesender","sends");
x.t("filesender","unzip");
x.t("filesender","process");
x.t("filesender","locate");
x.t("sends","image");
x.t("local","machine");
x.t("ctp","client");
x.t("ctp","clinical");
x.t("ctp","server");
x.t("unzip","file");
x.t("submitting","images");
x.t("steps","installing");
x.t("client","filesender");
x.t("client","anonymizes");
x.t("client","forwards");
x.t("database","repository");
x.t("rsna","clinical");
x.t("tools","local");
x.t("involves","following");
x.t("process","follows");
x.t("process","involves");
x.t("(s)","internet");
x.t("(s)","nbia");
x.t("(s)","rsna");
x.t("(s)","submitted");
x.t("script","filesender");
x.t("data","comply");
x.t("image","submission");
x.t("image","nbia");
x.t("image","(s)");
x.t("image","configuration/submission");
x.t("submit","image");
x.t("locate","image");
x.t("submitted","update");
x.t("patient","privacy");
x.t("configuration/submission","methods");
x.t("following","steps");
x.t("anonymizes","data");
x.t("using","filesender");
x.t("alternative","image");
x.t("comply","patient");
x.t("forwards","image");
x.t("clinical","trial");
x.t("update","anonymization");
x.t("server","transfers");
x.t("server","ctp");
}
