/*L
 *  Copyright SAIC, Ellumen and RSNA (CTP)
 *
 *
 *  Distributed under the OSI-approved BSD 3-Clause License.
 *  See http://ncip.github.com/national-biomedical-image-archive/LICENSE.txt for details.
 */

function FileData_Pairs(x)
{
x.t("submission","user");
x.t("create","new");
x.t("required","fields");
x.t("required","information");
x.t("once","submitted");
x.t("asterisk","required");
x.t("user","register");
x.t("user","getting");
x.t("user","items");
x.t("user","registering");
x.t("user","account");
x.t("user","nbia");
x.t("user","information");
x.t("execute","submission");
x.t("register","execute");
x.t("register","new");
x.t("register","hypertext");
x.t("conveyed","nbia");
x.t("administrator","create");
x.t("form","opens");
x.t("form","message");
x.t("new","user");
x.t("new","nbia");
x.t("getting","started");
x.t("link","continue");
x.t("link","login");
x.t("items","asterisk");
x.t("clicking","link");
x.t("entry","form");
x.t("registering","new");
x.t("account","utp");
x.t("creating","new");
x.t("nbia","user");
x.t("nbia","administrator");
x.t("nbia","registering");
x.t("nbia","nbia");
x.t("nbia","welcome");
x.t("cancel","return");
x.t("welcome","login");
x.t("indicate","agreement");
x.t("continue","registration");
x.t("started","nbia");
x.t("fields","click");
x.t("legal","rules");
x.t("review","legal");
x.t("button","review");
x.t("utp","information");
x.t("hypertext","link");
x.t("opens","enter");
x.t("follow","steps");
x.t("steps","click");
x.t("registration","form");
x.t("return","login");
x.t("login","button");
x.t("login","screen");
x.t("login","page");
x.t("message","conveyed");
x.t("click","register");
x.t("click","cancel");
x.t("click","blue");
x.t("road","page");
x.t("enter","required");
x.t("rules","road");
x.t("agreement","click");
x.t("screen","once");
x.t("page","indicate");
x.t("page","follow");
x.t("information","new");
x.t("information","creating");
x.t("information","click");
x.t("blue","clicking");
x.t("submitted","entry");
}
