/*L
 *  Copyright SAIC, Ellumen and RSNA (CTP)
 *
 *
 *  Distributed under the OSI-approved BSD 3-Clause License.
 *  See http://ncip.github.com/national-biomedical-image-archive/LICENSE.txt for details.
 */

function FileData_Pairs(x)
{
x.t("toc","button");
x.t("full","online");
x.t("table","contents");
x.t("once","online");
x.t("related","topics");
x.t("topic","once");
x.t("helps","locate");
x.t("bar","open");
x.t("icon","button");
x.t("displays","left");
x.t("displays","top");
x.t("displays","online");
x.t("open","full");
x.t("open","closely");
x.t("open","complete");
x.t("open","context");
x.t("left","title");
x.t("left","panel");
x.t("form","page");
x.t("text","box");
x.t("text","search");
x.t("getting","started");
x.t("access","online");
x.t("contents","displays");
x.t("contents","panel");
x.t("top","table");
x.t("top","left");
x.t("top","menu");
x.t("top","page");
x.t("closely","related");
x.t("entering","query");
x.t("menu","bar");
x.t("menu","option");
x.t("complete","online");
x.t("logged","nbia");
x.t("buttons","help");
x.t("nbia","software");
x.t("nbia","click");
x.t("nbia","online");
x.t("nbia","following");
x.t("nbia","using");
x.t("searches","help");
x.t("perform","word");
x.t("methods","click");
x.t("search","text");
x.t("started","nbia");
x.t("array","options");
x.t("button","top");
x.t("options","helps");
x.t("written","help");
x.t("software","access");
x.t("index","tab");
x.t("directory","follow");
x.t("hypertext","links");
x.t("interest","context-sensitive");
x.t("correspond","form");
x.t("follow","hypertext");
x.t("master","nbia");
x.t("option","top");
x.t("click","toc");
x.t("click","help");
x.t("project","access");
x.t("project","index");
x.t("title","bar");
x.t("panel","perform");
x.t("panel","online");
x.t("word","searches");
x.t("online","help");
x.t("help","icon");
x.t("help","displays");
x.t("help","getting");
x.t("help","entering");
x.t("help","menu");
x.t("help","nbia");
x.t("help","array");
x.t("help","written");
x.t("help","directory");
x.t("help","master");
x.t("help","project");
x.t("help","online");
x.t("help","topics");
x.t("help","opened");
x.t("help","using");
x.t("help","without");
x.t("page","open");
x.t("page","help");
x.t("context","sensitive");
x.t("sensitive","topic");
x.t("query","text");
x.t("locate","topics");
x.t("topics","open");
x.t("topics","buttons");
x.t("topics","interest");
x.t("topics","correspond");
x.t("topics","locate");
x.t("topics","using");
x.t("opened","click");
x.t("following","methods");
x.t("links","related");
x.t("using","table");
x.t("using","nbia");
x.t("tab","displays");
x.t("without","logged");
x.t("context-sensitive","help");
}
