function FileData_Pairs(x)
{
x.t("home","page");
x.t("displays","several");
x.t("getting","started");
x.t("menu","bars");
x.t("nbia","home");
x.t("nbia","using");
x.t("nbia","welcome/home");
x.t("started","nbia");
x.t("panels","menu");
x.t("opens","login");
x.t("login","displays");
x.t("several","panels");
x.t("page","getting");
x.t("page","nbia");
x.t("page","opens");
x.t("page","using");
x.t("using","nbia");
x.t("welcome/home","page");
}
