/*L
 *  Copyright SAIC, Ellumen and RSNA (CTP)
 *
 *
 *  Distributed under the OSI-approved BSD 3-Clause License.
 *  See http://ncip.github.com/national-biomedical-image-archive/LICENSE.txt for details.
 */

function FileData_Pairs(x)
{
x.t("human","services");
x.t("institute","center");
x.t("institute","nbia");
x.t("digital","imaging");
x.t("user","interface");
x.t("cip","cancer");
x.t("program","dicom");
x.t("interface","hhs");
x.t("center","bioinformatics");
x.t("health","human");
x.t("referred","nbia");
x.t("graphical","user");
x.t("definition","cabig");
x.t("nbia","glossary");
x.t("nbia","national");
x.t("nbia","online");
x.t("cabig","cancer");
x.t("war","web");
x.t("glossary","nbia");
x.t("glossary","term");
x.t("glossary","acronyms");
x.t("biomedical","imaging");
x.t("biomedical","informatics");
x.t("web","application");
x.t("cancer","institute");
x.t("cancer","biomedical");
x.t("cancer","imaging");
x.t("grid","cip");
x.t("national","biomedical");
x.t("national","cancer");
x.t("communications","medicine");
x.t("gui","graphical");
x.t("hhs","health");
x.t("medicine","gui");
x.t("term","definition");
x.t("imaging","program");
x.t("imaging","communications");
x.t("imaging","archive");
x.t("dicom","digital");
x.t("services","nci");
x.t("online","help");
x.t("help","described");
x.t("bioinformatics","war");
x.t("archive","ncicb");
x.t("application","resource");
x.t("described","glossary");
x.t("nci","national");
x.t("ncicb","national");
x.t("informatics","grid");
x.t("acronyms","referred");
}
