/*L
 *  Copyright SAIC, Ellumen and RSNA (CTP)
 *
 *
 *  Distributed under the OSI-approved BSD 3-Clause License.
 *  See http://ncip.github.com/national-biomedical-image-archive/LICENSE.txt for details.
 */

function FileData_Pairs(x)
{
x.t("csv","file");
x.t("possible","replacing");
x.t("lists","editing");
x.t("lists","created");
x.t("comment","hyperlink");
x.t("create","exporting");
x.t("create","export");
x.t("instance","ids");
x.t("upload","doing");
x.t("doing","replaces");
x.t("sidebar","edit");
x.t("current","shared");
x.t("backing","shared");
x.t("later","creating");
x.t("working","data");
x.t("working","shared");
x.t("displays","list");
x.t("open","page");
x.t("left","sidebar");
x.t("delete","shared");
x.t("editing","shared");
x.t("link","tools");
x.t("want","upload");
x.t("want","edit");
x.t("details","list");
x.t("list","possible");
x.t("list","create");
x.t("list","open");
x.t("list","editing");
x.t("list","link");
x.t("list","want");
x.t("list","browse");
x.t("list","edit");
x.t("list","uploading");
x.t("list","viewing");
x.t("list","cannot");
x.t("list","follow");
x.t("list","exporting");
x.t("list","page");
x.t("list","data");
x.t("list","information");
x.t("list","shared");
x.t("list",".csv");
x.t("file","create");
x.t("file","later");
x.t("file","want");
x.t("file","series");
x.t("results","working");
x.t("browse",".csv");
x.t("creating","editing");
x.t("name","shared");
x.t("edit","details");
x.t("edit","list");
x.t("edit","shared");
x.t("provides","relevant");
x.t("search","results");
x.t("yourself","edit");
x.t("uploading","csv");
x.t("viewing","search");
x.t("basket","working");
x.t("basket","export");
x.t("edited","shared");
x.t("cannot","delete");
x.t("opens","displays");
x.t("hyperlink","provides");
x.t("follow","steps");
x.t("steps","click");
x.t("replaces","current");
x.t("ids","list");
x.t("ids",".csv");
x.t("click","name");
x.t("click","edit");
x.t("enter","appropriate");
x.t("consider","backing");
x.t("exporting","shared");
x.t("tools","left");
x.t("page","opens");
x.t("page","enter");
x.t("data","basket");
x.t("information","edit");
x.t("information","edited");
x.t("shared","lists");
x.t("shared","list");
x.t("image","series");
x.t("appropriate","comment");
x.t("replacing","consider");
x.t("export","image");
x.t("export","shared");
x.t(".csv","file");
x.t("created","yourself");
x.t("created","click");
x.t("relevant","information");
x.t("series","instance");
}
