/*L
 *  Copyright SAIC, Ellumen and RSNA (CTP)
 *
 *
 *  Distributed under the OSI-approved BSD 3-Clause License.
 *  See http://ncip.github.com/national-biomedical-image-archive/LICENSE.txt for details.
 */

function FileData_Pairs(x)
{
x.t("latest","release");
x.t("right","hand");
x.t("files","information");
x.t("refer","https://imaging.nci.nih.gov");
x.t("related","files");
x.t("download","latest");
x.t("download","center");
x.t("download","menu");
x.t("download","page");
x.t("provided","center");
x.t("center","download");
x.t("center","panelof");
x.t("hand","corner");
x.t("getting","started");
x.t("link","upper");
x.t("link","site");
x.t("link","ncicb");
x.t("upper","right");
x.t("list","site");
x.t("corner","nbia");
x.t("menu","option");
x.t("nbia","related");
x.t("nbia","portal");
x.t("nbia","using");
x.t("map","getting");
x.t("map","link");
x.t("map","portal");
x.t("map","click");
x.t("map","takes");
x.t("map","information");
x.t("started","nbia");
x.t("portal","portal");
x.t("portal","site");
x.t("portal","page");
x.t("display","list");
x.t("panelof","page");
x.t("release","nbia");
x.t("option","link");
x.t("click","download");
x.t("click","site");
x.t("takes","download");
x.t("site","map");
x.t("page","link");
x.t("page","display");
x.t("page","click");
x.t("information","refer");
x.t("information","provided");
x.t("ncicb","download");
x.t("using","nbia");
}
