/*L
 *  Copyright SAIC, Ellumen and RSNA (CTP)
 *
 *
 *  Distributed under the OSI-approved BSD 3-Clause License.
 *  See http://ncip.github.com/national-biomedical-image-archive/LICENSE.txt for details.
 */

function FileData_Pairs(x)
{
x.t("hidden","login");
x.t("managing","data");
x.t("home","page");
x.t("gigabytes","data");
x.t("user","bypass");
x.t("remote","searches");
x.t("download","gigabytes");
x.t("public","data");
x.t("time","application");
x.t("default","that's");
x.t("default","additionally");
x.t("getting","started");
x.t("access","public");
x.t("access","login");
x.t("access","without");
x.t("link","home");
x.t("link","default");
x.t("able","search");
x.t("add","data");
x.t("expanded","default");
x.t("logged","public");
x.t("logged","application");
x.t("images","using");
x.t("features","welcome");
x.t("that's","case");
x.t("visualizing","images");
x.t("account","access");
x.t("nbia","simply");
x.t("nbia","using");
x.t("nbia","returns");
x.t("nbia","without");
x.t("searches","visualizing");
x.t("logging","getting");
x.t("logging","data");
x.t("logging","using");
x.t("logging","log");
x.t("perform","tasks");
x.t("welcome","page");
x.t("search","functions");
x.t("search","function");
x.t("search","query");
x.t("search","image");
x.t("decision","may");
x.t("started","nbia");
x.t("local","installation");
x.t("cedara","software");
x.t("begin","features");
x.t("functions","search");
x.t("functions","unavailable");
x.t("configured","enable");
x.t("configured","disable");
x.t("viewing","image");
x.t("function","guest");
x.t("basket","logged");
x.t("basket","information");
x.t("annotations","remote");
x.t("software","cannot");
x.t("cannot","download");
x.t("may","made");
x.t("section","hidden");
x.t("section","expanded");
x.t("simply","begin");
x.t("enable","public");
x.t("enable","guest");
x.t("guest","add");
x.t("guest","account");
x.t("guest","without");
x.t("login","link");
x.t("login","perform");
x.t("login","section");
x.t("login","application");
x.t("made","enable");
x.t("saving","search");
x.t("bypass","login");
x.t("page","cases");
x.t("page","including");
x.t("data","time");
x.t("data","access");
x.t("data","nbia");
x.t("data","basket");
x.t("data","guest");
x.t("data","data");
x.t("information","managing");
x.t("query","viewing");
x.t("image","link");
x.t("image","annotations");
x.t("application","functions");
x.t("application","configured");
x.t("unavailable","saving");
x.t("disable","guest");
x.t("case","user");
x.t("cases","local");
x.t("using","nbia");
x.t("using","cedara");
x.t("additionally","able");
x.t("installation","decision");
x.t("returns","without");
x.t("without","logged");
x.t("without","logging");
x.t("without","login");
x.t("including","search");
x.t("log","access");
}
