/*L
 *  Copyright SAIC, Ellumen and RSNA (CTP)
 *
 *
 *  Distributed under the OSI-approved BSD 3-Clause License.
 *  See http://ncip.github.com/national-biomedical-image-archive/LICENSE.txt for details.
 */

function FileData_Pairs(x)
{
x.t("available","logged");
x.t("description","description");
x.t("description","displays");
x.t("description","editing");
x.t("description","nbia");
x.t("description","edit");
x.t("description","collection");
x.t("description","follow");
x.t("description","drop-down");
x.t("description","administration");
x.t("sidebar","click");
x.t("user","feature");
x.t("user","knows");
x.t("formatting","tools");
x.t("administrator","enter");
x.t("displays","simple/advanced");
x.t("type","data");
x.t("left","sidebar");
x.t("editing","collection");
x.t("text","formatting");
x.t("text","box");
x.t("text","appropriate");
x.t("new","nbia");
x.t("list","select");
x.t("upt","information");
x.t("add","hyperlink");
x.t("logged","users");
x.t("creating","new");
x.t("name","text");
x.t("box","enter");
x.t("nbia","user");
x.t("nbia","administration");
x.t("edit","collection");
x.t("edit","existing");
x.t("allows","administrator");
x.t("search","screen");
x.t("resource","wiki");
x.t("wiki","longer");
x.t("next","collection");
x.t("collection","description");
x.t("collection","text");
x.t("collection","name");
x.t("collection","nbia");
x.t("collection","edit");
x.t("collection","privileges");
x.t("feature","available");
x.t("feature","allows");
x.t("select","collection");
x.t("button","next");
x.t("admin","tools");
x.t("format","text");
x.t("hyperlink","resource");
x.t("follow","steps");
x.t("steps","admin");
x.t("comprises","collection");
x.t("enter","description");
x.t("enter","brief");
x.t("click","edit");
x.t("click","button");
x.t("existing","description");
x.t("longer","description");
x.t("brief","description");
x.t("tools","left");
x.t("tools","format");
x.t("knows","type");
x.t("drop-down","list");
x.t("screen","click");
x.t("privileges","defined");
x.t("information","creating");
x.t("data","comprises");
x.t("defined","upt");
x.t("appropriate","add");
x.t("administration","editing");
x.t("administration","feature");
x.t("users","manage");
x.t("simple/advanced","search");
x.t("manage","collection");
}
