/*L
 *  Copyright SAIC, Ellumen and RSNA (CTP)
 *
 *
 *  Distributed under the OSI-approved BSD 3-Clause License.
 *  See http://ncip.github.com/national-biomedical-image-archive/LICENSE.txt for details.
 */

function FileData_Pairs(x)
{
x.t("study","series");
x.t("indicated","contains");
x.t("within","series");
x.t("annotation","files");
x.t("files","indicated");
x.t("downloaded","download");
x.t("drills","down");
x.t("submissions","nbia");
x.t("subject","details");
x.t("subject","click");
x.t("download","series");
x.t("hierarchy","submissions");
x.t("down","search");
x.t("automatically","downloaded");
x.t("details","studies");
x.t("items","clicking");
x.t("objects","downloaded");
x.t("clicking","add");
x.t("add","items--the");
x.t("add","basket");
x.t("results","subject");
x.t("results","add");
x.t("results","images");
x.t("results","overview");
x.t("results","studies");
x.t("results","nbia");
x.t("results","search");
x.t("results","display");
x.t("results","important");
x.t("results","click");
x.t("images","within");
x.t("images","search");
x.t("images","links");
x.t("images","series");
x.t("overview","search");
x.t("overview","viewing");
x.t("overview","reviewing");
x.t("thumbnail","images");
x.t("studies","subject");
x.t("studies","display");
x.t("studies","links");
x.t("nbia","drills");
x.t("nbia","collection");
x.t("search","results");
x.t("entire","patient");
x.t("revealing","thumbnail");
x.t("items--the","entire");
x.t("review","hierarchy");
x.t("display","results");
x.t("display","revealing");
x.t("display","first");
x.t("point","process");
x.t("collection","patient");
x.t("first","search");
x.t("button","identifies");
x.t("viewing","search");
x.t("basket","button");
x.t("basket","selecting");
x.t("annotations","column");
x.t("important","review");
x.t("identifies","objects");
x.t("click","show");
x.t("selecting","items");
x.t("process","reviewing");
x.t("show","images");
x.t("show","studies");
x.t("data","basket");
x.t("reviewing","results");
x.t("reviewing","search");
x.t("patient","study");
x.t("patient","(subject)");
x.t("column","automatically");
x.t("(subject)","study");
x.t("links","results");
x.t("links","search");
x.t("series","annotation");
x.t("series","images");
x.t("series","display");
x.t("series","point");
x.t("series","data");
x.t("contains","annotations");
}
