/*L
 *  Copyright SAIC, Ellumen and RSNA (CTP)
 *
 *
 *  Distributed under the OSI-approved BSD 3-Clause License.
 *  See http://ncip.github.com/national-biomedical-image-archive/LICENSE.txt for details.
 */

function FileData_Pairs(x)
{
x.t("available","logged");
x.t("rather","waiting");
x.t("deleting","image");
x.t("sidebar","click");
x.t("user","function");
x.t("execute","online");
x.t("execute","real");
x.t("job","manually");
x.t("delete","execute");
x.t("delete","admin");
x.t("delete","series");
x.t("left","sidebar");
x.t("time","series");
x.t("removes","images");
x.t("listed","page");
x.t("new","nbia");
x.t("link","nbia");
x.t("list","image");
x.t("upt","information");
x.t("logged","users");
x.t("images","approved");
x.t("creating","new");
x.t("nbia","user");
x.t("nbia","opens");
x.t("nbia","administration");
x.t("part","two-tier");
x.t("perform","online");
x.t("next","scheduled");
x.t("system-wide","deletion");
x.t("feature","available");
x.t("function","part");
x.t("function","immediately");
x.t("admin","execute");
x.t("admin","tools");
x.t("admin","privileges");
x.t("opens","list");
x.t("approving","image");
x.t("follow","steps");
x.t("steps","admin");
x.t("click","delete");
x.t("click","perform");
x.t("tools","left");
x.t("process","delete");
x.t("waiting","next");
x.t("deletion","rather");
x.t("deletion","job");
x.t("deletion","link");
x.t("deletion","function");
x.t("deletion","approving");
x.t("deletion","click");
x.t("deletion","process");
x.t("deletion","image");
x.t("online","deletion");
x.t("page","deleted");
x.t("privileges","defined");
x.t("information","creating");
x.t("removal","series");
x.t("image","deletions");
x.t("image","series");
x.t("defined","upt");
x.t("approved","deletion");
x.t("administration","deleting");
x.t("administration","feature");
x.t("users","delete");
x.t("immediately","removes");
x.t("real","time");
x.t("scheduled","system-wide");
x.t("individual","series");
x.t("manually","deleting");
x.t("manually","delete");
x.t("series","listed");
x.t("series","nbia");
x.t("series","follow");
x.t("series","online");
x.t("series","removal");
x.t("series","approved");
x.t("series","administration");
x.t("series","manually");
x.t("two-tier","deletion");
x.t("deleted","specify");
x.t("specify","individual");
}
