/*L
 *  Copyright SAIC, Ellumen and RSNA (CTP)
 *
 *
 *  Distributed under the OSI-approved BSD 3-Clause License.
 *  See http://ncip.github.com/national-biomedical-image-archive/LICENSE.txt for details.
 */

function FileData_Pairs(x)
{
x.t("satisfied","click");
x.t("[patient]","study");
x.t("study","series");
x.t("deselect","items");
x.t("exist","images");
x.t("tables","select");
x.t("subject","[patient]");
x.t("working","data");
x.t("items","check");
x.t("items","basket");
x.t("items","individually");
x.t("items","added");
x.t("items","given");
x.t("add","items");
x.t("add","basket");
x.t("results","tables");
x.t("results","working");
x.t("results","page");
x.t("check","boxes");
x.t("check","uncheck");
x.t("images","series");
x.t("buttons","above");
x.t("boxes","exist");
x.t("boxes","items");
x.t("search","results");
x.t("select","deselect");
x.t("select","items");
x.t("button","items");
x.t("button","page");
x.t("viewing","search");
x.t("basket","satisfied");
x.t("basket","subject");
x.t("basket","add");
x.t("basket","button");
x.t("basket","viewing");
x.t("basket","adding");
x.t("basket","highlighted");
x.t("individually","check");
x.t("added","basket");
x.t("added","data");
x.t("given","search");
x.t("click","add");
x.t("click","corresponding");
x.t("page","images");
x.t("page","click");
x.t("page","initiated");
x.t("data","basket");
x.t("uncheck","buttons");
x.t("above","search");
x.t("corresponding","check");
x.t("adding","items");
x.t("series","added");
x.t("series","page");
x.t("series","levels");
x.t("levels","select");
x.t("initiated","task");
x.t("highlighted","page");
}
