/*L
 *  Copyright SAIC, Ellumen and RSNA (CTP)
 *
 *
 *  Distributed under the OSI-approved BSD 3-Clause License.
 *  See http://ncip.github.com/national-biomedical-image-archive/LICENSE.txt for details.
 */

function FileData_Pairs(x)
{
x.t("just","submitted");
x.t("within","collection");
x.t("create","protection");
x.t("(pg)","data");
x.t("once","submitted");
x.t("pgs","access");
x.t("pgs","created");
x.t("user","groups");
x.t("user","protection");
x.t("until","notified");
x.t("administrator","create");
x.t("administrator","upt");
x.t("administrator","information");
x.t("element","collection/project");
x.t("element","per");
x.t("access","imaging");
x.t("security","newly");
x.t("security","image");
x.t("upt","security");
x.t("upt","nbia");
x.t("upt","configuration");
x.t("group","(pg)");
x.t("group","roles");
x.t("assign","users");
x.t("images","configuring");
x.t("configuring","security");
x.t("name","nbia");
x.t("acronym","upt");
x.t("nbia","administrator");
x.t("nbia","nbia");
x.t("nbia","national");
x.t("changed","nbia");
x.t("dependent","upon");
x.t("biomedical","imaging");
x.t("cancer","imaging");
x.t("national","biomedical");
x.t("national","cancer");
x.t("collection","projects");
x.t("submitting","images");
x.t("assigned","upt");
x.t("notified","otherwise");
x.t("groups","pgs");
x.t("least","site");
x.t("least","protection");
x.t("projects","least");
x.t("upon","roles");
x.t("specifically","create");
x.t("imaging","data");
x.t("imaging","archive");
x.t("configuration","remains");
x.t("collection/project","separate");
x.t("separate","protection");
x.t("site","within");
x.t("site","pes");
x.t("data","just");
x.t("data","once");
x.t("data","administrator");
x.t("data","configuring");
x.t("data","nbia");
x.t("data","dependent");
x.t("data","submitting");
x.t("information","assigning");
x.t("archive","until");
x.t("archive","changed");
x.t("newly","submitted");
x.t("image","data");
x.t("protection","element");
x.t("protection","group");
x.t("protection","elements");
x.t("submitted","specifically");
x.t("submitted","data");
x.t("users","user");
x.t("otherwise","acronym");
x.t("created","assign");
x.t("elements","(pe)");
x.t("(pe)","least");
x.t("per","site");
x.t("assigning","user");
x.t("pes","pgs");
x.t("roles","name");
x.t("roles","assigned");
x.t("remains","ncia");
}
