/*L
 *  Copyright SAIC, Ellumen and RSNA (CTP)
 *
 *
 *  Distributed under the OSI-approved BSD 3-Clause License.
 *  See http://ncip.github.com/national-biomedical-image-archive/LICENSE.txt for details.
 */

function FileData_Pairs(x)
{
x.t("(dcp)","displays");
x.t("institute","link");
x.t("dcp","web");
x.t("table","information");
x.t("description","nbia");
x.t("sidebar","left");
x.t("sidebar","getting");
x.t("sidebar","portal");
x.t("program","(ctep)");
x.t("program","(cip)");
x.t("cip","web");
x.t("bar","portal");
x.t("displays","dcp");
x.t("displays","cip");
x.t("displays","ctep");
x.t("center","bioinformatics");
x.t("left","sidebar");
x.t("left","side");
x.t("down","collaborators");
x.t("browser","window");
x.t("division","cancer");
x.t("getting","started");
x.t("consists","options");
x.t("link","nbia");
x.t("link","cabig");
x.t("link","nci");
x.t("link","ncicb");
x.t("ctep","web");
x.t("(ctep)","displays");
x.t("nbia","portal");
x.t("nbia","application");
x.t("nbia","using");
x.t("cabig","link");
x.t("cabig","quick");
x.t("window","quick");
x.t("window","collaborators");
x.t("biomedical","informatics");
x.t("web","site");
x.t("started","nbia");
x.t("cancer","institute");
x.t("cancer","biomedical");
x.t("cancer","prevention");
x.t("cancer","imaging");
x.t("cancer","therapy");
x.t("quick","links");
x.t("portal","portal");
x.t("portal","page");
x.t("prevention","(dcp)");
x.t("national","cancer");
x.t("grid","cabig");
x.t("options","quick");
x.t("options","described");
x.t("side","bar");
x.t("collaborators","division");
x.t("collaborators","consists");
x.t("collaborators","cancer");
x.t("collaborators","nci");
x.t("option","description");
x.t("imaging","program");
x.t("evaluation","program");
x.t("page","left");
x.t("page","down");
x.t("site","separate");
x.t("separate","browser");
x.t("bioinformatics","link");
x.t("information","quick");
x.t("application","collaborators");
x.t("application","contains");
x.t("described","following");
x.t("nci","center");
x.t("nci","cancer");
x.t("nci","quick");
x.t("following","table");
x.t("links","cancer");
x.t("links","national");
x.t("links","options");
x.t("links","option");
x.t("links","nci");
x.t("(cip)","displays");
x.t("using","nbia");
x.t("informatics","grid");
x.t("therapy","evaluation");
x.t("contains","link");
}
