/*L
 *  Copyright SAIC, Ellumen and RSNA (CTP)
 *
 *
 *  Distributed under the OSI-approved BSD 3-Clause License.
 *  See http://ncip.github.com/national-biomedical-image-archive/LICENSE.txt for details.
 */

function FileData_Pairs(x)
{
x.t("managing","saved");
x.t("managing","data");
x.t("saved","queries");
x.t("table","option");
x.t("description","information");
x.t("submission","status");
x.t("submission","assign");
x.t("submission","verifies");
x.t("submission","reports");
x.t("home","page");
x.t("sidebar","home");
x.t("sidebar","left");
x.t("sidebar","getting");
x.t("sidebar","welcome");
x.t("displays","saved");
x.t("displays","dicom");
x.t("displays","data");
x.t("displays","query");
x.t("(qc)","tool");
x.t("left","sidebar");
x.t("evaluate","submission");
x.t("down","queries");
x.t("getting","started");
x.t("consists","options");
x.t("contents","displays");
x.t("status","report");
x.t("status","using");
x.t("assign","status");
x.t("nbia","home");
x.t("nbia","using");
x.t("welcome","page");
x.t("window","obtaining");
x.t("verifies","image");
x.t("allows","curator");
x.t("started","nbia");
x.t("viewers","displays");
x.t("viewers","data");
x.t("quality","control");
x.t("queries","displays");
x.t("queries","consists");
x.t("queries","queries");
x.t("queries","view");
x.t("queries","page");
x.t("options","described");
x.t("viewing","submission");
x.t("viewing","query");
x.t("control","(qc)");
x.t("viewer","links");
x.t("basket","queries");
x.t("basket","view");
x.t("basket","page");
x.t("report","viewing");
x.t("verify","submission");
x.t("option","description");
x.t("dicom","viewers");
x.t("dicom","viewer");
x.t("dicom","image");
x.t("tools","verify");
x.t("tools","dicom");
x.t("tools","tool");
x.t("obtaining","dicom");
x.t("view","saved");
x.t("view","contents");
x.t("view","query");
x.t("page","managing");
x.t("page","home");
x.t("page","left");
x.t("page","down");
x.t("page","viewing");
x.t("information","tools");
x.t("data","basket");
x.t("query","history");
x.t("tool","allows");
x.t("tool","tools");
x.t("image","submission");
x.t("image","viewers");
x.t("curator","evaluate");
x.t("described","following");
x.t("history","displays");
x.t("history","tools");
x.t("history","page");
x.t("following","table");
x.t("links","window");
x.t("using","nbia");
x.t("using","quality");
}
