/*L
 *  Copyright SAIC, Ellumen and RSNA (CTP)
 *
 *
 *  Distributed under the OSI-approved BSD 3-Clause License.
 *  See http://ncip.github.com/national-biomedical-image-archive/LICENSE.txt for details.
 */

function FileData_Pairs(x)
{
x.t("email","new");
x.t("available","using");
x.t("instance","nbia");
x.t("sidebar","option");
x.t("directs","nci");
x.t("user","change");
x.t("user","received");
x.t("user","appropriate");
x.t("user","password");
x.t("current","reset");
x.t("change","password");
x.t("reset","password");
x.t("time","during");
x.t("left","sidebar");
x.t("text","box");
x.t("getting","started");
x.t("new","reset");
x.t("link","directs");
x.t("choice","time");
x.t("during","tenure");
x.t("3.1","longer");
x.t("box","follow");
x.t("nbia","user");
x.t("nbia","change");
x.t("nbia","prior");
x.t("nbia","welcome");
x.t("nbia","follow");
x.t("nbia","changing");
x.t("nbia","passwords");
x.t("nbia","using");
x.t("prior","3.1");
x.t("welcome","page");
x.t("continue","reset");
x.t("web","site");
x.t("started","nbia");
x.t("tenure","nbia");
x.t("present","ncicb");
x.t("feature","available");
x.t("section","left");
x.t("follow","steps");
x.t("follow","directions");
x.t("steps","log");
x.t("previous","user");
x.t("option","present");
x.t("given","web");
x.t("click","change");
x.t("enter","nci");
x.t("changing","user");
x.t("longer","work");
x.t("tools","section");
x.t("cbiit","instance");
x.t("page","click");
x.t("site","change");
x.t("received","email");
x.t("appropriate","text");
x.t("application","previous");
x.t("nci","user");
x.t("nci","password");
x.t("work","application");
x.t("ncicb","instance");
x.t("following","directions");
x.t("using","current");
x.t("using","cbiit");
x.t("passwords","versions");
x.t("password","change");
x.t("password","getting");
x.t("password","link");
x.t("password","choice");
x.t("password","nbia");
x.t("password","continue");
x.t("password","feature");
x.t("password","changing");
x.t("password","tools");
x.t("password","following");
x.t("password","using");
x.t("password","station");
x.t("directions","change");
x.t("directions","given");
x.t("versions","nbia");
x.t("log","nbia");
x.t("station","enter");
}
