/*L
 *  Copyright SAIC, Ellumen and RSNA (CTP)
 *
 *
 *  Distributed under the OSI-approved BSD 3-Clause License.
 *  See http://ncip.github.com/national-biomedical-image-archive/LICENSE.txt for details.
 */

function FileData_Pairs(x)
{
x.t("3gb","total");
x.t("3gb","size");
x.t("below","http");
x.t("files","below");
x.t("files","displays");
x.t("files","nbia");
x.t("files","button");
x.t("files","click");
x.t("files","using");
x.t("once","file");
x.t("downloaded","displays");
x.t("downloaded","local");
x.t("download","files");
x.t("download","items");
x.t("download","file");
x.t("download","limit");
x.t("download","completed");
x.t("download","threshold");
x.t("download","manager");
x.t("download","data");
x.t("download","including");
x.t("until","download");
x.t("until","remove");
x.t("working","data");
x.t("displays","until");
x.t("displays","progress");
x.t("bar","updates");
x.t("bar","show");
x.t("workstation","status");
x.t("total","size");
x.t("items","download");
x.t("items","http");
x.t("items","viewing");
x.t("updates","once");
x.t("size","selected");
x.t("size","above");
x.t("http","download");
x.t("http","http");
x.t("http","threshold");
x.t("file","downloaded");
x.t("file","100");
x.t("file","zipped");
x.t("status","download");
x.t("add","data");
x.t("results","working");
x.t("logged","download");
x.t("exceed","limit");
x.t("remove","something");
x.t("leaving","download");
x.t("path","destination");
x.t("nbia","hides");
x.t("nbia","zips");
x.t("nbia","warns");
x.t("limit","cannot");
x.t("limit","relaxed");
x.t("limit","data");
x.t("alternatively","login");
x.t("completed","logged");
x.t("search","results");
x.t("destination","file");
x.t("local","workstation");
x.t("selected","files");
x.t("progress","download");
x.t("progress","bar");
x.t("hides","download");
x.t("something","basket");
x.t("button","download");
x.t("button","leaving");
x.t("button","click");
x.t("viewing","search");
x.t("stops","add");
x.t("basket","download");
x.t("basket","limit");
x.t("basket","alternatively");
x.t("basket","downloading");
x.t("cannot","download");
x.t("threshold","nbia");
x.t("threshold","click");
x.t("threshold","greater");
x.t("threshold","less");
x.t("100","zipped");
x.t("login","data");
x.t("relaxed","download");
x.t("click","download");
x.t("enter","path");
x.t("greater","3gb");
x.t("less","3gb");
x.t("manager","download");
x.t("manager","button");
x.t("manager","information");
x.t("show","progress");
x.t("data","until");
x.t("data","exceed");
x.t("data","nbia");
x.t("data","basket");
x.t("above","http");
x.t("downloading","data");
x.t("zips","files");
x.t("zipped","progress");
x.t("zipped","enter");
x.t("percent","downloaded");
x.t("using","download");
x.t("including","percent");
x.t("warns","stops");
}
