/**
 * XmlException.java
 *
 * This file was generated by MapForce 2011r2sp1.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the MapForce Documentation for further details.
 * http://www.altova.com/mapforce
 */


package com.altova.xml;


public class XmlException extends com.altova.AltovaException {
	public XmlException(String text) {
		super(text);
	}

	public XmlException(Exception other) {
		super(other);
	}
}
