function FileData_Pairs(x)
{
x.t("deleting","nbia");
x.t("deleting","image");
x.t("administrator","assist");
x.t("granted","specific");
x.t("assist","two-tier");
x.t("nbia","data");
x.t("nbia","administration");
x.t("processes","approving");
x.t("deletions","manually");
x.t("approving","image");
x.t("specific","roles");
x.t("process","deleting");
x.t("deletion","processes");
x.t("data","granted");
x.t("information","roles");
x.t("image","deletions");
x.t("image","series");
x.t("administration","deleting");
x.t("series","deleting");
x.t("series","administrator");
x.t("series","nbia");
x.t("two-tier","process");
x.t("manually","deleting");
x.t("roles","deletion");
x.t("roles","information");
}
